services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tinyUrl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111111
    ports:
      - '5433:5432'
    volumes:
      - tiny-url-postgres-data:/var/lib/postgresql/data

volumes:
  tiny-url-postgres-data:
